---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iofog-operator
  labels:
    name: iofog-operator
spec:
  selector:
    matchLabels:
      name: iofog-operator
  replicas: 1
  template:
    metadata:
      labels:
        name: iofog-operator
    spec:
      serviceAccountName: iofog-operator
      containers:
      - command:
        - iofog-operator
        args:
        - --enable-leader-election
        image: ghcr.io/datasance/operator@sha256:a9273412b66db888df060e112187c5dc9eca2a488c47160abe37134fe3ba4226
        imagePullPolicy: Always
        name: iofog-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: iofog-operator
      terminationGracePeriodSeconds: 10
